development:
  adapter: postgresql
  database: poetrybin_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: poetrybin_test
  pool: 5
  timeout: 5000

cucumber:
  <<: *test